export const dummyProducts = [
  {
    id: 531,
    name: "1.3 Mp IP-Camera TR-D2111 (3.6 Mm)",
    img: "/images/prod1.webp",
    price: 15.0,
    oldPrice: 20.0,
    category: "Media",
  },
  {
    id: 544,
    name: "2.8 Mp IP-Camera TR-D234 (3.6 Mm)",
    img: "/images/prod2.webp",
    price: 55.5,
    category: "Media",
  },
  {
    id: 546,
    name: "3.2 Mp IP-Camera TR-E800 (3.6 Mm)",
    img: "/images/prod3.webp",
    price: 60.5,
    category: "Media",
  },
  {
    id: 547,
    name: "Camera Battery TR-D233 (3.6 Mm)",
    img: "/images/prod4.webp",
    price: 70.0,
    category: "Media",
  },
  {
    id: 548,
    name: "Network Camera 720p Enigma DS-I100",
    img: "/images/prod5.webp",
    price: 70.0,
    category: "Media",
  },
  {
    id: 545,
    name: "Omega DHL22 F600 Monitor LCD 21.5″",
    img: "/images/prod6.webp",
    price: 80.5,
    category: "Media",
  },
];
